describe('Hermes Upload', {retries: 0}, () => {
  it('uploads a dataset', () => {
    cy.intercept('POST', '**/api/login').as('loginRequest');
    cy.intercept('POST', '**/api/upload-hermes').as('uploadRequest');
    cy.visit('/hermes/login');
    cy.get('input[id="email"]').type('uploader1');
    cy.get('input[type="password"]').type('password');
    cy.contains('button', 'Sign In').click();
    cy.wait('@loginRequest');
    cy.visit('/hermes/new', { timeout: 10000 });
    cy.get('#dataSetName').type('Cypress dataset');
    // cy.get('#genomeBuild').type('GRCh38').type('{enter}');
    cy.get('#cohort').type('UKBiobank');
    cy.get('#contactPerson').type('Point of Contact');
    cy.get('#dataCollectionStart').type('2006/01/01');
    cy.get('[data-cy="sex"]').type('Male').type('{enter}');
    cy.get('#dataCollectionEnd').type('2006/01/31');
    cy.get('[data-cy="ancestry"]').type('European').type('{enter}');
    cy.get('[data-cy="case-ascertainment"]').eq(0).type('Electronic').type('{enter}');
    cy.get("#phenotype").type('T2D');
    cy.get("#caseDefinition").type("My case definition");
    cy.get("#totalSampleSize").type("989");
    cy.get("#maleProportionCohort").type("1");
    cy.get('#callingAlgorithm').type("You called, algorithm?");
    cy.get('#genotypingArray').type("Array against you");
    cy.get('[data-cy="referenceGenome"]').type('Hg19').type('{enter}');
    cy.get('#imputationSoftware').type('Imputate this software');
    cy.get('#imputationReference').type('Imputation reference');
    cy.get('#numberOfVariantsForImputation').type('47');
    cy.get('#imputationQualityMeasure').type('highest quality');

    // cy.get("#participants").type('20');
    // cy.get("#sexProportion").type('20');
    // cy.get("#age").type('20');
    // cy.get("#analysisSoftware").type('Big Analysis Software');
    // cy.get("#statisticalModel").type('Complex Model');
    // cy.get("#covariates").type('Here are some covariates');
    cy.get('input[type="file"]').attachFile('sample-gwas.csv');
    cy.get('[data-cy="column-dropdown"]').eq(1).type('chromosome').type('{enter}');
    cy.get('[data-cy="column-dropdown"]').eq(2).type('position').type('{enter}');
    cy.get('[data-cy="column-dropdown"]').eq(3).type('alt').type('{enter}');
    cy.get('[data-cy="column-dropdown"]').eq(4).type('reference').type('{enter}');
    cy.get('[data-cy="column-dropdown"]').eq(5).type('eaf').type('{enter}');
    cy.get('[data-cy="column-dropdown"]').eq(6).type('beta').type('{enter}');
    cy.get('[data-cy="column-dropdown"]').eq(7).type('stdErr').type('{enter}');
    cy.get('[data-cy="column-dropdown"]').eq(8).type('pVale').type('{enter}');
    cy.get('[data-cy="column-dropdown"]').eq(9).type('n').type('{enter}');
    cy.get('[data-cy="column-dropdown"]').eq(10).type('Impute').type('{enter}');
    cy.get('button[aria-label="Upload"]').click();
    cy.wait('@uploadRequest');
    cy.wait(500);
    cy.location('pathname').should('eq', '/hermes');
    cy.contains('td', 'Cypress dataset').should('exist');
  });
});
