<template>
    <div
														class="row"
														id="scoreColumnsConfig"
													>
														<div
															class="col-md-6 col"
														>
															<div class="label">
																Score columns
																<sup
																	class="
																		optional
																	"
																	>Select type
																	to calculate
																	score
																</sup>
															</div>
															<ul
																class="
																	dr-byor-data-columns
																"
															>
																<li>
																	CHR<label>
																		<select
																			class="
																				form-control
																			"
																		>
																			<option>
																				None
																			</option>
																			<option>
																				Boolean
																			</option>
																		</select></label
																	>
																</li>
																<li>
																	POS<label>
																		<select
																			class="
																				form-control
																			"
																		>
																			<option>
																				None
																			</option>
																			<option>
																				Boolean
																			</option>
																		</select></label
																	>
																</li>
																<li>
																	REF<label>
																		<select
																			class="
																				form-control
																			"
																		>
																			<option>
																				None
																			</option>
																			<option>
																				Boolean
																			</option>
																		</select></label
																	>
																</li>
																<li>
																	ALT<label>
																		<select
																			class="
																				form-control
																			"
																		>
																			<option>
																				None
																			</option>
																			<option>
																				Boolean
																			</option>
																		</select></label
																	>
																</li>
																<li>
																	RSID<label>
																		<select
																			class="
																				form-control
																			"
																		>
																			<option>
																				None
																			</option>
																			<option>
																				Boolean
																			</option>
																		</select></label
																	>
																</li>
																<li>
																	PVAL<label>
																		<select
																			class="
																				form-control
																			"
																		>
																			<option>
																				None
																			</option>
																			<option>
																				Boolean
																			</option>
																		</select></label
																	>
																</li>
															</ul>
														</div>
														<div
															class="col-md-6 col"
														>
															<div class="label">
																Add
																'value:score'
																pair separated
																by comma
															</div>
															<ul
																class="
																	dr-byor-data-columns
																"
															>
																<li>
																	CHR<input
																		type="text"
																		class="
																			form-control
																			input-default
																		"
																		placeholder="true:1,false:0"
																	/>
																</li>
																<li>
																	POS<input
																		type="text"
																		class="
																			form-control
																			input-default
																		"
																		placeholder="true:1,false:0"
																	/>
																</li>
															</ul>
														</div>
													</div>
</template>
<style scoped>
    @import "public/css/mdkp.css";
    @import "public/css/configbuilder.css";
</style>
