<template>
    <div>
<h5>
												Data convert
												<sup class="optional"
													>Tutorial
												</sup>
											</h5>

											<div class="row dr-builder-ui">
												<div class="col-md-3 col">
													<div class="label">
														Type
													</div>
													<select
														class="form-control"
													>
														<option value="">
															Array to string<sup
																>*</sup
															>
														</option>
														<option value="">
															Calculate
														</option>
														<option value="">
															Join
														</option>
														<option value="">
															Join multi
														</option>
														<option value="">
															Raw (rename)
														</option>
														<option value="">
															Replace characters
														</option>
														<option value="">
															Score columns
														</option>
													</select>
													<pre />
													<div class="label">
														New field name
													</div>
													<input
														type="text"
														class="
															form-control
															input-default
														"
														placeholder="name"
													/>
												</div>
												<div class="col-md-8 col">
													<!-- raw -->
													<div
														class="row"
														id="rawConfig"
													>
														<div
															class="col-md-6 col"
														>
															<div class="label">
																Raw (rename) |
																Select field
															</div>
															<ul
																class="
																	dr-byor-data-columns
																"
															>
																<li
																	class="
																		form-check
																		form-check-inline
																	"
																>
																	<input
																		class="
																			form-check-input
																		"
																		type="radio"
																		value=""
																		id="flexCheckDefault"
																	/>
																	<span
																		class="
																			form-check-label
																		"
																		for="flexCheckDefault"
																	>
																		CHR
																	</span>
																</li>
																<li
																	class="
																		form-check
																		form-check-inline
																	"
																>
																	<input
																		class="
																			form-check-input
																		"
																		type="radio"
																		value=""
																		id="flexCheckDefault"
																	/>
																	<span
																		class="
																			form-check-label
																		"
																		for="flexCheckDefault"
																	>
																		POS</span
																	>
																</li>

																<li
																	class="
																		form-check
																		form-check-inline
																	"
																>
																	<input
																		class="
																			form-check-input
																		"
																		type="radio"
																		value=""
																		id="flexCheckDefault"
																	/>
																	<span
																		class="
																			form-check-label
																		"
																		for="flexCheckDefault"
																	>
																		REF
																	</span>
																</li>
																<li
																	class="
																		form-check
																		form-check-inline
																	"
																>
																	<input
																		class="
																			form-check-input
																		"
																		type="radio"
																		value=""
																		id="flexCheckDefault"
																	/>
																	<span
																		class="
																			form-check-label
																		"
																		for="flexCheckDefault"
																	>
																		ALT
																	</span>
																</li>
																<li
																	class="
																		form-check
																		form-check-inline
																	"
																>
																	<input
																		class="
																			form-check-input
																		"
																		type="radio"
																		value=""
																		id="flexCheckDefault"
																	/>
																	<span
																		class="
																			form-check-label
																		"
																		for="flexCheckDefault"
																	>
																		RSID
																	</span>
																</li>
																<li
																	class="
																		form-check
																		form-check-inline
																	"
																>
																	<input
																		class="
																			form-check-input
																		"
																		type="radio"
																		value=""
																		id="flexCheckDefault"
																	/>
																	<span
																		class="
																			form-check-label
																		"
																		for="flexCheckDefault"
																	>
																		PVAL
																	</span>
																</li>
															</ul>
														</div>
														<div
															class="col-md-6 col"
														></div>
													</div>
													<!-- calculate -->
													<div
														class="row"
														id="calculateConfig"
													>
														<div
															class="col-md-6 col"
														>
															<div class="label">
																Calculate |
																Select field
															</div>
															<ul
																class="
																	dr-byor-data-columns
																"
															>
																<li
																	class="
																		form-check
																		form-check-inline
																	"
																>
																	<input
																		class="
																			form-check-input
																		"
																		type="radio"
																		value=""
																		id="flexCheckDefault"
																	/>
																	<span
																		class="
																			form-check-label
																		"
																		for="flexCheckDefault"
																	>
																		CHR
																	</span>
																</li>
																<li
																	class="
																		form-check
																		form-check-inline
																	"
																>
																	<input
																		class="
																			form-check-input
																		"
																		type="radio"
																		value=""
																		id="flexCheckDefault"
																	/>
																	<span
																		class="
																			form-check-label
																		"
																		for="flexCheckDefault"
																	>
																		POS</span
																	>
																</li>

																<li
																	class="
																		form-check
																		form-check-inline
																	"
																>
																	<input
																		class="
																			form-check-input
																		"
																		type="radio"
																		value=""
																		id="flexCheckDefault"
																	/>
																	<span
																		class="
																			form-check-label
																		"
																		for="flexCheckDefault"
																	>
																		REF
																	</span>
																</li>
																<li
																	class="
																		form-check
																		form-check-inline
																	"
																>
																	<input
																		class="
																			form-check-input
																		"
																		type="radio"
																		value=""
																		id="flexCheckDefault"
																	/>
																	<span
																		class="
																			form-check-label
																		"
																		for="flexCheckDefault"
																	>
																		ALT
																	</span>
																</li>
																<li
																	class="
																		form-check
																		form-check-inline
																	"
																>
																	<input
																		class="
																			form-check-input
																		"
																		type="radio"
																		value=""
																		id="flexCheckDefault"
																	/>
																	<span
																		class="
																			form-check-label
																		"
																		for="flexCheckDefault"
																	>
																		RSID
																	</span>
																</li>
																<li
																	class="
																		form-check
																		form-check-inline
																	"
																>
																	<input
																		class="
																			form-check-input
																		"
																		type="radio"
																		value=""
																		id="flexCheckDefault"
																	/>
																	<span
																		class="
																			form-check-label
																		"
																		for="flexCheckDefault"
																	>
																		PVAL
																	</span>
																</li>
															</ul>
														</div>
														<div
															class="col-md-6 col"
														>
															<div class="label">
																Calculate
															</div>
															<select
																class="
																	form-control
																"
															>
																<option>
																	-Log10
																</option>
															</select>
														</div>
													</div>
													<!-- join -->
													<div
														class="row"
														id="joinConfig"
													>
														<div
															class="col-md-6 col"
														>
															<div class="label">
																Join | Select
																field(s)
																<sup
																	class="
																		optional
																	"
																	>Set weight
																	to select
																</sup>
															</div>
															<ul
																class="
																	dr-byor-data-columns
																"
															>
																<li>
																	CHR<label>
																		<select
																			class="
																				form-control
																			"
																		>
																			<option>
																				None
																			</option>
																			<option>
																				0
																			</option>
																			<option>
																				1
																			</option>
																		</select></label
																	>
																</li>
																<li>
																	POS<label>
																		<select
																			class="
																				form-control
																			"
																		>
																			<option>
																				None
																			</option>
																			<option>
																				0
																			</option>
																			<option>
																				1
																			</option>
																		</select></label
																	>
																</li>
																<li>
																	REF<label>
																		<select
																			class="
																				form-control
																			"
																		>
																			<option>
																				None
																			</option>
																			<option>
																				0
																			</option>
																			<option>
																				1
																			</option>
																		</select></label
																	>
																</li>
																<li>
																	ALT<label>
																		<select
																			class="
																				form-control
																			"
																		>
																			<option>
																				None
																			</option>
																			<option>
																				0
																			</option>
																			<option>
																				1
																			</option>
																		</select></label
																	>
																</li>
																<li>
																	RSID<label>
																		<select
																			class="
																				form-control
																			"
																		>
																			<option>
																				None
																			</option>
																			<option>
																				0
																			</option>
																			<option>
																				1
																			</option>
																		</select></label
																	>
																</li>
																<li>
																	PVAL<label>
																		<select
																			class="
																				form-control
																			"
																		>
																			<option>
																				None
																			</option>
																			<option>
																				0
																			</option>
																			<option>
																				1
																			</option>
																		</select></label
																	>
																</li>
															</ul>
														</div>
														<div
															class="col-md-6 col"
														>
															<div class="label">
																Join by
															</div>
															<ul
																class="
																	dr-byor-data-columns
																"
															>
																<li>
																	CHR<label
																		><input
																			type="text"
																			class="
																				form-control
																				input-default
																			"
																		/>
																	</label>
																</li>
																<li>POS</li>
															</ul>
														</div>
													</div>
													<!-- join multi -->
													<div
														class="row"
														id="joinMultiConfig"
													>
														<div
															class="col-md-6 col"
														>
															<div class="label">
																Join multi |
																Select field(s)
																<sup
																	class="
																		optional
																	"
																	>Set weight
																	to select
																</sup>
															</div>
															<ul
																class="
																	dr-byor-data-columns
																"
															>
																<li>
																	CHR<label>
																		<select
																			class="
																				form-control
																			"
																		>
																			<option>
																				None
																			</option>
																			<option>
																				0
																			</option>
																			<option>
																				1
																			</option>
																			<option>
																				2
																			</option>
																			<option>
																				3
																			</option>
																			<option>
																				4
																			</option>
																			<option>
																				5
																			</option>
																		</select></label
																	>
																</li>
																<li>
																	POS<label>
																		<select
																			class="
																				form-control
																			"
																		>
																			<option>
																				None
																			</option>
																			<option>
																				0
																			</option>
																			<option>
																				1
																			</option>
																			<option>
																				2
																			</option>
																			<option>
																				3
																			</option>
																			<option>
																				4
																			</option>
																			<option>
																				5
																			</option>
																		</select></label
																	>
																</li>
																<li>
																	REF<label>
																		<select
																			class="
																				form-control
																			"
																		>
																			<option>
																				None
																			</option>
																			<option>
																				0
																			</option>
																			<option>
																				1
																			</option>
																			<option>
																				2
																			</option>
																			<option>
																				3
																			</option>
																			<option>
																				4
																			</option>
																			<option>
																				5
																			</option>
																		</select></label
																	>
																</li>
																<li>
																	ALT<label>
																		<select
																			class="
																				form-control
																			"
																		>
																			<option>
																				None
																			</option>
																			<option>
																				0
																			</option>
																			<option>
																				1
																			</option>
																			<option>
																				2
																			</option>
																			<option>
																				3
																			</option>
																			<option>
																				4
																			</option>
																			<option>
																				5
																			</option>
																		</select></label
																	>
																</li>
																<li>
																	RSID<label>
																		<select
																			class="
																				form-control
																			"
																		>
																			<option>
																				None
																			</option>
																			<option>
																				0
																			</option>
																			<option>
																				1
																			</option>
																			<option>
																				2
																			</option>
																			<option>
																				3
																			</option>
																			<option>
																				4
																			</option>
																			<option>
																				5
																			</option>
																		</select></label
																	>
																</li>
																<li>
																	PVAL<label>
																		<select
																			class="
																				form-control
																			"
																		>
																			<option>
																				None
																			</option>
																			<option>
																				0
																			</option>
																			<option>
																				1
																			</option>
																			<option>
																				2
																			</option>
																			<option>
																				3
																			</option>
																			<option>
																				4
																			</option>
																			<option>
																				5
																			</option>
																		</select></label
																	>
																</li>
															</ul>
														</div>
														<div
															class="col-md-6 col"
														>
															<div class="label">
																Join by
															</div>
															<ul
																class="
																	dr-byor-data-columns
																"
															>
																<li>
																	CHR<label
																		><input
																			type="text"
																			class="
																				form-control
																				input-default
																			"
																		/>
																	</label>
																</li>
																<li>
																	POS<label>
																		<input
																			type="text"
																			class="
																				form-control
																				input-default
																			"
																	/></label>
																</li>
																<li>
																	REF<label>
																		<input
																			type="text"
																			class="
																				form-control
																				input-default
																			"
																	/></label>
																</li>
																<li>ALT</li>
															</ul>
														</div>
													</div>
													<!-- array to string -->
													<div
														class="row"
														id="array2StringConfig"
													>
														<div
															class="col-md-6 col"
														>
															<div class="label">
																Array to string
																| Select field
															</div>
															<ul
																class="
																	dr-byor-data-columns
																"
															>
																<li
																	class="
																		form-check
																		form-check-inline
																	"
																>
																	<input
																		class="
																			form-check-input
																		"
																		type="radio"
																		value=""
																		id="flexCheckDefault"
																	/>
																	<span
																		class="
																			form-check-label
																		"
																		for="flexCheckDefault"
																	>
																		CHR
																	</span>
																</li>
																<li
																	class="
																		form-check
																		form-check-inline
																	"
																>
																	<input
																		class="
																			form-check-input
																		"
																		type="radio"
																		value=""
																		id="flexCheckDefault"
																	/>
																	<span
																		class="
																			form-check-label
																		"
																		for="flexCheckDefault"
																	>
																		POS</span
																	>
																</li>

																<li
																	class="
																		form-check
																		form-check-inline
																	"
																>
																	<input
																		class="
																			form-check-input
																		"
																		type="radio"
																		value=""
																		id="flexCheckDefault"
																	/>
																	<span
																		class="
																			form-check-label
																		"
																		for="flexCheckDefault"
																	>
																		REF
																	</span>
																</li>
																<li
																	class="
																		form-check
																		form-check-inline
																	"
																>
																	<input
																		class="
																			form-check-input
																		"
																		type="radio"
																		value=""
																		id="flexCheckDefault"
																	/>
																	<span
																		class="
																			form-check-label
																		"
																		for="flexCheckDefault"
																	>
																		ALT
																	</span>
																</li>
																<li
																	class="
																		form-check
																		form-check-inline
																	"
																>
																	<input
																		class="
																			form-check-input
																		"
																		type="radio"
																		value=""
																		id="flexCheckDefault"
																	/>
																	<span
																		class="
																			form-check-label
																		"
																		for="flexCheckDefault"
																	>
																		RSID
																	</span>
																</li>
																<li
																	class="
																		form-check
																		form-check-inline
																	"
																>
																	<input
																		class="
																			form-check-input
																		"
																		type="radio"
																		value=""
																		id="flexCheckDefault"
																	/>
																	<span
																		class="
																			form-check-label
																		"
																		for="flexCheckDefault"
																	>
																		PVAL
																	</span>
																</li>
															</ul>
														</div>
														<div
															class="col-md-6 col"
														>
															<div class="label">
																Separate items
																by
															</div>
															<input
																type="text"
																class="
																	form-control
																	input-default
																"
															/>
														</div>
													</div>
													<!-- replace characters -->
													<div
														class="row"
														id="replaceCharactersConfig"
													>
														<div
															class="col-md-6 col"
														>
															<div class="label">
																Replace
																characters |
																Select field
															</div>
															<ul
																class="
																	dr-byor-data-columns
																"
															>
																<li
																	class="
																		form-check
																		form-check-inline
																	"
																>
																	<input
																		class="
																			form-check-input
																		"
																		type="radio"
																		value=""
																		id="flexCheckDefault"
																	/>
																	<span
																		class="
																			form-check-label
																		"
																		for="flexCheckDefault"
																	>
																		CHR
																	</span>
																</li>
																<li
																	class="
																		form-check
																		form-check-inline
																	"
																>
																	<input
																		class="
																			form-check-input
																		"
																		type="radio"
																		value=""
																		id="flexCheckDefault"
																	/>
																	<span
																		class="
																			form-check-label
																		"
																		for="flexCheckDefault"
																	>
																		POS</span
																	>
																</li>

																<li
																	class="
																		form-check
																		form-check-inline
																	"
																>
																	<input
																		class="
																			form-check-input
																		"
																		type="radio"
																		value=""
																		id="flexCheckDefault"
																	/>
																	<span
																		class="
																			form-check-label
																		"
																		for="flexCheckDefault"
																	>
																		REF
																	</span>
																</li>
																<li
																	class="
																		form-check
																		form-check-inline
																	"
																>
																	<input
																		class="
																			form-check-input
																		"
																		type="radio"
																		value=""
																		id="flexCheckDefault"
																	/>
																	<span
																		class="
																			form-check-label
																		"
																		for="flexCheckDefault"
																	>
																		ALT
																	</span>
																</li>
																<li
																	class="
																		form-check
																		form-check-inline
																	"
																>
																	<input
																		class="
																			form-check-input
																		"
																		type="radio"
																		value=""
																		id="flexCheckDefault"
																	/>
																	<span
																		class="
																			form-check-label
																		"
																		for="flexCheckDefault"
																	>
																		RSID
																	</span>
																</li>
																<li
																	class="
																		form-check
																		form-check-inline
																	"
																>
																	<input
																		class="
																			form-check-input
																		"
																		type="radio"
																		value=""
																		id="flexCheckDefault"
																	/>
																	<span
																		class="
																			form-check-label
																		"
																		for="flexCheckDefault"
																	>
																		PVAL
																	</span>
																</li>
															</ul>
														</div>
														<div
															class="col-md-6 col"
														>
															<div class="label">
																Add
																'string|replacing_string'
																pair per line.
															</div>
															<textarea
																rows="3"
																class="
																	form-control
																"
																placeholder="example|replace"
															>
															</textarea>
														</div>
													</div>
													<!-- Score columns -->
													<div
														class="row"
														id="scoreColumnsConfig"
													>
														<div
															class="col-md-6 col"
														>
															<div class="label">
																Score columns
																<sup
																	class="
																		optional
																	"
																	>Select type
																	to calculate
																	score
																</sup>
															</div>
															<ul
																class="
																	dr-byor-data-columns
																"
															>
																<li>
																	CHR<label>
																		<select
																			class="
																				form-control
																			"
																		>
																			<option>
																				None
																			</option>
																			<option>
																				Boolean
																			</option>
																		</select></label
																	>
																</li>
																<li>
																	POS<label>
																		<select
																			class="
																				form-control
																			"
																		>
																			<option>
																				None
																			</option>
																			<option>
																				Boolean
																			</option>
																		</select></label
																	>
																</li>
																<li>
																	REF<label>
																		<select
																			class="
																				form-control
																			"
																		>
																			<option>
																				None
																			</option>
																			<option>
																				Boolean
																			</option>
																		</select></label
																	>
																</li>
																<li>
																	ALT<label>
																		<select
																			class="
																				form-control
																			"
																		>
																			<option>
																				None
																			</option>
																			<option>
																				Boolean
																			</option>
																		</select></label
																	>
																</li>
																<li>
																	RSID<label>
																		<select
																			class="
																				form-control
																			"
																		>
																			<option>
																				None
																			</option>
																			<option>
																				Boolean
																			</option>
																		</select></label
																	>
																</li>
																<li>
																	PVAL<label>
																		<select
																			class="
																				form-control
																			"
																		>
																			<option>
																				None
																			</option>
																			<option>
																				Boolean
																			</option>
																		</select></label
																	>
																</li>
															</ul>
														</div>
														<div
															class="col-md-6 col"
														>
															<div class="label">
																Add
																'value:score'
																pair separated
																by comma
															</div>
															<ul
																class="
																	dr-byor-data-columns
																"
															>
																<li>
																	CHR<input
																		type="text"
																		class="
																			form-control
																			input-default
																		"
																		placeholder="true:1,false:0"
																	/>
																</li>
																<li>
																	POS<input
																		type="text"
																		class="
																			form-control
																			input-default
																		"
																		placeholder="true:1,false:0"
																	/>
																</li>
															</ul>
														</div>
													</div>
												</div>
												<div class="col-md-1 col">
													<button
														class="
															btn
															btn-primary
															btn-sm
														"
														type="button"
													>
														Save
													</button>
													<button
														class="
															btn
															btn-warning
															btn-sm
														"
														type="button"
													>
														Cancel
													</button>
													<button
														class="
															btn
															btn-danger
															btn-sm
														"
														type="button"
													>
														Delete
													</button>
												</div>
											</div>
    </div>
</template>
<style scoped>
@import "public/css/mdkp.css";
@import "public/css/configbuilder.css";
</style>
<script setup>
    import "bootstrap/dist/css/bootstrap.min.css";
	import "bootstrap-icons/font/bootstrap-icons.css";
    import ArrayToString from "@/components/configcomponents/dataconverters/ArrayToString.vue";
    import Calculate from "@/components/configcomponents/dataconverters/Calculate.vue";
    import Join from "@/components/configcomponents/dataconverters/Join.vue";
    import JoinMulti from "@/components/configcomponents/dataconverters/JoinMulti.vue";
    import RawRename from "@/components/configcomponents/dataconverters/RawRename.vue";
    import ReplaceCharacters from "@/components/configcomponents/dataconverters/ReplaceCharacters.vue";
    import ScoreColumns from "@/components/configcomponents/dataconverters/ScoreColumns.vue";
</script>