name: CI

on:
  push:
    branches:
      - "main"
    tags:
      - 'V*.*.*'

jobs:

  deploy-qa:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Deploy to QA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy
        with:
          deploy-environment: 'dev'
          host: ${{ secrets.DEPLOY_HOST }}
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}

  deploy-prod:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/V')
    name: Deploy to Prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy
        with:
          deploy-environment: 'prod'
          host: ${{ secrets.DEPLOY_HOST }}
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          tag-name: ${{ github.ref_name }}
