name: CI

on:
    push:
        branches:
            - "*"
        tags:
            - "V*.*.*"

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install

            - name: Lint
              run: npm run lint

            - name: Run tests
              run: npm run test

    deploy-qa:
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        name: Deploy to QA
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/deploy
              with:
                  deploy-environment: "dev"
                  host: ${{ secrets.DEPLOY_HOST }}
                  private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    deploy-prod:
        needs: [test]
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/V')
        name: Deploy to Prod
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/deploy
              with:
                  deploy-environment: "prod"
                  host: ${{ secrets.DEPLOY_HOST }}
                  private-key: ${{ secrets.SSH_PRIVATE_KEY }}
                  tag-name: ${{ github.ref_name }}
